/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as adminRouteRouteImport } from './routes/(admin)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as publicAuthRouteRouteImport } from './routes/(public)/auth/route'
import { Route as adminPermissionsIndexRouteImport } from './routes/(admin)/permissions/index'
import { Route as adminDashboardIndexRouteImport } from './routes/(admin)/dashboard/index'
import { Route as publicAuthSignInIndexRouteImport } from './routes/(public)/auth/sign-in/index'

const adminRouteRoute = adminRouteRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAuthRouteRoute = publicAuthRouteRouteImport.update({
  id: '/(public)/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const adminPermissionsIndexRoute = adminPermissionsIndexRouteImport.update({
  id: '/permissions/',
  path: '/permissions/',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminDashboardIndexRoute = adminDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => adminRouteRoute,
} as any)
const publicAuthSignInIndexRoute = publicAuthSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => publicAuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof adminRouteRouteWithChildren
  '/auth': typeof publicAuthRouteRouteWithChildren
  '/dashboard': typeof adminDashboardIndexRoute
  '/permissions': typeof adminPermissionsIndexRoute
  '/auth/sign-in': typeof publicAuthSignInIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof adminRouteRouteWithChildren
  '/auth': typeof publicAuthRouteRouteWithChildren
  '/dashboard': typeof adminDashboardIndexRoute
  '/permissions': typeof adminPermissionsIndexRoute
  '/auth/sign-in': typeof publicAuthSignInIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(admin)': typeof adminRouteRouteWithChildren
  '/(public)/auth': typeof publicAuthRouteRouteWithChildren
  '/(admin)/dashboard/': typeof adminDashboardIndexRoute
  '/(admin)/permissions/': typeof adminPermissionsIndexRoute
  '/(public)/auth/sign-in/': typeof publicAuthSignInIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/dashboard' | '/permissions' | '/auth/sign-in'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/dashboard' | '/permissions' | '/auth/sign-in'
  id:
    | '__root__'
    | '/'
    | '/(admin)'
    | '/(public)/auth'
    | '/(admin)/dashboard/'
    | '/(admin)/permissions/'
    | '/(public)/auth/sign-in/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  adminRouteRoute: typeof adminRouteRouteWithChildren
  publicAuthRouteRoute: typeof publicAuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(admin)': {
      id: '/(admin)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof adminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/auth': {
      id: '/(public)/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof publicAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/permissions/': {
      id: '/(admin)/permissions/'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof adminPermissionsIndexRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/dashboard/': {
      id: '/(admin)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof adminDashboardIndexRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(public)/auth/sign-in/': {
      id: '/(public)/auth/sign-in/'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof publicAuthSignInIndexRouteImport
      parentRoute: typeof publicAuthRouteRoute
    }
  }
}

interface adminRouteRouteChildren {
  adminDashboardIndexRoute: typeof adminDashboardIndexRoute
  adminPermissionsIndexRoute: typeof adminPermissionsIndexRoute
}

const adminRouteRouteChildren: adminRouteRouteChildren = {
  adminDashboardIndexRoute: adminDashboardIndexRoute,
  adminPermissionsIndexRoute: adminPermissionsIndexRoute,
}

const adminRouteRouteWithChildren = adminRouteRoute._addFileChildren(
  adminRouteRouteChildren,
)

interface publicAuthRouteRouteChildren {
  publicAuthSignInIndexRoute: typeof publicAuthSignInIndexRoute
}

const publicAuthRouteRouteChildren: publicAuthRouteRouteChildren = {
  publicAuthSignInIndexRoute: publicAuthSignInIndexRoute,
}

const publicAuthRouteRouteWithChildren = publicAuthRouteRoute._addFileChildren(
  publicAuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  adminRouteRoute: adminRouteRouteWithChildren,
  publicAuthRouteRoute: publicAuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
